I added Azerbaijani Dataset
lk-geimfari/mimesis pull request #1599
Opened 2024-09-24 08:27 UTC by ferid333

I added Azerbaijani Dataset

2024-09-24 09:11 UTC, lk-geimfari commented
Hi! Please see https://github.com/lk-geimfari/mimesis/tree/master/mimesis/datasets/locale_template

2024-09-24 09:43 UTC, ferid333 commented
Sorry I will fix

2024-09-25 07:23 UTC, ferid333 commented
Hello. Everything works fine but there is problem related to language. In our language if a person is female, surname of her should be added 'a' at the end. For example, Afaq Qurbanov**a** but for males Farid Qurbanov

2024-09-25 16:44 UTC, lk-geimfari commented
> Hello. Everything works fine but there is problem related to language. In our language if a person is female, surname of her should be added 'a' at the end. For example, Afaq Qurbanov**a** but for males Farid Qurbanov

Same in Russian. Please, refer to `ru` locale.

2024-09-26 06:06 UTC, ferid333 commented
I just update the surnames, everything is fine now and working

2024-09-26 10:51 UTC, lk-geimfari commented
@ferid333 We're almost done. Please fix the tests and add locale to the table of locales: https://github.com/lk-geimfari/mimesis/blob/master/docs/locales.rst#supported-locales

2024-09-26 11:05 UTC, ferid333 commented
@lk-geimfari Error is related  to this function:  Where SUPPORTED_LOCALES_COUNT does not match
def test_locale_enum():
>       assert len(list(Locale)) == SUPPORTED_LOCALES_COUNT
E       AssertionError: assert 48 == 47
E        +  where 48 = len([<Locale.AR_AE: 'ar-ae'>, <Locale.AR_DZ: 'ar-dz'>, <Locale.AR_EG: 'ar-eg'>, <Locale.AR_JO: 'ar-jo'>, <Locale.AR_OM: 'ar-om'>, <Locale.AR_KW: 'ar-kw'>, ...])
E        +    where [<Locale.AR_AE: 'ar-ae'>, <Locale.AR_DZ: 'ar-dz'>, <Locale.AR_EG: 'ar-eg'>, <Locale.AR_JO: 'ar-jo'>, <Locale.AR_OM: 'ar-om'>, <Locale.AR_KW: 'ar-kw'>, ...] = list(Locale)

2024-09-26 11:14 UTC, lk-geimfari commented
> @lk-geimfari Error is related to this function: Where SUPPORTED_LOCALES_COUNT does not match def test_locale_enum():
> 
> > ```
> >   assert len(list(Locale)) == SUPPORTED_LOCALES_COUNT
> > ```
> 
> E AssertionError: assert 48 == 47 E + where 48 = len([<Locale.AR_AE: 'ar-ae'>, <Locale.AR_DZ: 'ar-dz'>, <Locale.AR_EG: 'ar-eg'>, <Locale.AR_JO: 'ar-jo'>, <Locale.AR_OM: 'ar-om'>, <Locale.AR_KW: 'ar-kw'>, ...]) E + where [<Locale.AR_AE: 'ar-ae'>, <Locale.AR_DZ: 'ar-dz'>, <Locale.AR_EG: 'ar-eg'>, <Locale.AR_JO: 'ar-jo'>, <Locale.AR_OM: 'ar-om'>, <Locale.AR_KW: 'ar-kw'>, ...] = list(Locale)

Yeah, I know. Contributors must increment the `SUPPORTED_LOCALES_COUNT` when adding a locale.

2024-09-26 11:20 UTC, ferid333 commented
> > @lk-geimfari Error is related to this function: Where SUPPORTED_LOCALES_COUNT does not match def test_locale_enum():
> > > ```
> > >   assert len(list(Locale)) == SUPPORTED_LOCALES_COUNT
> > > ```
> > 
> > 
> > E AssertionError: assert 48 == 47 E + where 48 = len([<Locale.AR_AE: 'ar-ae'>, <Locale.AR_DZ: 'ar-dz'>, <Locale.AR_EG: 'ar-eg'>, <Locale.AR_JO: 'ar-jo'>, <Locale.AR_OM: 'ar-om'>, <Locale.AR_KW: 'ar-kw'>, ...]) E + where [<Locale.AR_AE: 'ar-ae'>, <Locale.AR_DZ: 'ar-dz'>, <Locale.AR_EG: 'ar-eg'>, <Locale.AR_JO: 'ar-jo'>, <Locale.AR_OM: 'ar-om'>, <Locale.AR_KW: 'ar-kw'>, ...] = list(Locale)
> 
> Yeah, I know. Contributors must increment the `SUPPORTED_LOCALES_COUNT` when adding a locale.

Where is that ?

2024-09-26 11:28 UTC, lk-geimfari commented
@ferid333 https://github.com/lk-geimfari/mimesis/blob/4212746d62d7f73a3cd85a0c3c2599a16928b3e2/tests/test_locales.py#L8

2024-09-26 22:07 UTC, lk-geimfari commented
@ferid333 Please, resolve conflicts.

2024-09-27 08:45 UTC, lk-geimfari commented
@ferid333 Some tests are still failing. Please, fix them. Thanks!

2024-09-27 10:52 UTC, ferid333 commented
@lk-geimfari  What error is related to ? CHECK=1 bash scripts/format.sh
Running lint check
would reformat /home/runner/work/mimesis/mimesis/mimesis/datasets/int/code.py
would reformat /home/runner/work/mimesis/mimesis/tests/test_locales.py
would reformat /home/runner/work/mimesis/mimesis/mimesis/datasets/int/finance.py

Oh no! 💥 💔 💥
3 files would be reformatted, 111 files would be left unchanged.
make: *** [Makefile:20: format] Error 1

2024-09-27 10:54 UTC, lk-geimfari commented
@ferid333 There are code style issues. You can fix them using `make format`

2024-09-28 11:06 UTC, ferid333 commented
> @ferid333 There are code style issues. You can fix them using `make format`

I made

2024-09-30 06:11 UTC, ferid333 commented
@lk-geimfari  What can be reason for that : @codecov
codecov
/ codecov/patch
mimesis/enums.py#L81
Added line #L81 was not covered by tests

2024-09-30 11:06 UTC, lk-geimfari requested changes

2024-09-30 11:06 UTC, lk-geimfari commented on mimesis/datasets/az/food.json
> +
Please, remove whitespaces.

2024-09-30 11:06 UTC, lk-geimfari commented on mimesis/datasets/az/text.json
> +}
Same here.

2024-10-01 06:03 UTC, ferid333 commented on pyproject.toml
> +isort = "^5.13.2"
@lk-geimfari I fixed. Thanks

2024-10-01 16:58 UTC, lk-geimfari commented
@ferid333 @ferid333 You forgot to lock dependencies after removing `isort`. Please lock deps, using `poetry lock`.

2024-10-02 10:04 UTC, lk-geimfari commented
@ferid333 We’re done. I’ll merge the PR later after a detailed review on my machine. Thank you!

2024-10-02 16:13 UTC, ferid333 commented
> @ferid333 We’re done. I’ll merge the PR later after a detailed review on my machine. Thank you!

Thank you

2024-11-26 05:15 UTC, ferid333 commented
Hello! Could you merge ?

2024-11-26 09:04 UTC, lk-geimfari commented
@ferid333 Sorry, I've been busy as hell these past few months.

2024-11-26 09:04 UTC, merged